- Create Tasks DAG

CREATE OR REPLACE TASK SUMMIT_23_COMMON_DB.DL_CORE.CUSTOMER_PROCESSED
WAREHOUSE = COMPUTE_M_WH
SCHEDULE = '60 MINUTE'
AS
CALL SUMMIT_23_COMMON_DB.DL_CORE.PROCESSED_SP('CUSTOMER','CUSTOMER_360','SUMMIT_23_RAW_DB','CUSTOMER','CUSTOMER','SUMMIT_23_PROCESSED_DB');

CREATE OR REPLACE TASK SUMMIT_23_COMMON_DB.DL_CORE.INVOICE_PROCESSED
    WAREHOUSE = COMPUTE_M_WH
    AFTER SUMMIT_23_COMMON_DB.DL_CORE.CUSTOMER_PROCESSED
AS
CALL SUMMIT_23_COMMON_DB.DL_CORE.INVOICE_PROCESS_SP();

CREATE OR REPLACE TASK SUMMIT_23_COMMON_DB.DL_CORE.SALES_ENRICH_CURATED
    WAREHOUSE = COMPUTE_XL_WH
    AFTER SUMMIT_23_COMMON_DB.DL_CORE.CUSTOMER_PROCESSED
AS
CALL SUMMIT_23_COMMON_DB.DL_CORE.SALES_ENRICH_SP();

--Enable tasks

ALTER TASK SUMMIT_23_COMMON_DB.DL_CORE.SALES_ENRICH_CURATED RESUME;
ALTER TASK SUMMIT_23_COMMON_DB.DL_CORE.INVOICE_PROCESSED RESUME;
ALTER TASK SUMMIT_23_COMMON_DB.DL_CORE.CUSTOMER_PROCESSED RESUME;